language: php
php:
  - 5.5
  - 5.4
  - 5.3
services:
  - elasticsearch
before_script:
  - sleep 3 # wait to make sure ES is up
before_install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.0.deb && sudo dpkg -i elasticsearch-1.3.0.deb && sudo service elasticsearch restart